version: '3.9'

services:

  node:
    container_name: server
    build: .
    restart: unless-stopped
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - port=${PORT}
    networks:
      - user-defined-bridge
    volumes:
      - ./src:/usr/app/src

  postgres:
    container_name: db
    image: postgres:alpine
    restart: unless-stopped
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - user-defined-bridge
    volumes:
      - dbdata:/var/lib/postgresql/data/
      - dblog:/var/log/

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: "example@mail.com"
  #     PGADMIN_DEFAULT_PASSWORD: "example"
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   ports:
  #     - "5050:80"
  #   restart: unless-stopped
  #   networks:
  #     - user-defined-bridge

networks:
  user-defined-bridge:
    driver: bridge

volumes:
  dbdata:
  dblog: