version: '3'
services:
  node:
    build: .
    restart: always
    ports: 
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - port=${PORT}
  postgres:
    build: ./database
    restart: always
    ports: 
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
